# Generated by Django 2.2.3 on 2019-09-28 07:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('display_name', models.CharField(max_length=50, verbose_name='Displayed Name')),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('display_name', models.CharField(max_length=50, verbose_name='Displayed Name')),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.IntegerField(unique=True)),
                ('date_of_admission', models.DateField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('father_name', models.CharField(max_length=50)),
                ('father_cnic', models.CharField(max_length=13)),
                ('fathers_phone_no', models.CharField(default='0000000', max_length=11)),
                ('fathers_proffesion', models.CharField(default='Not Set', max_length=50)),
                ('address', models.CharField(default='Not Set', max_length=150)),
                ('is_studying', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(blank=True, upload_to=students.models.user_directory_path)),
                ('current_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateField(default=datetime.date(2019, 10, 1), verbose_name='Valid Until')),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('fee_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.FeeGroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.Student')),
            ],
        ),
        migrations.AddField(
            model_name='feegroup',
            name='fee_types',
            field=models.ManyToManyField(to='students.FeeType'),
        ),
    ]
